credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$e10MIwevm9pAmXMIEzMZiuE9mIPBZvrlCK6lnyACzaFFkSBazJGpa # abc To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$XQwBwO8fXbfX07wfZ7JJ4OLZm4uAZEE8qs/NpfewVACH.AoBZQxR # def To be replaced with hashed password
      
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - cc33233@gmail.com